### ISSUE TITLE
Add support for MySQL lookups

### ISSUE THREAD

**Issue by n4580** [keith/investigate.vim#17]
Could you add MySQL and / or PosgreSQL lookups in Dash for `.sql` files?

**Comment by keith** [comment]
Definitely, would you like to submit a PR for this? Looks like you'd add that like about here: https://github.com/keith/investigate.vim/blob/master/autoload/investigate/defaults.vim#L38

**Comment by keith** [comment]
Please feel free to submit a PR for this! I'll merge it if you do! Thanks!
