### ISSUE TITLE
Does not work on visual selection

### ISSUE THREAD

**Issue by zhuochun** [keith/investigate.vim#18]
`gK` is mapped to normal mode.

In visual mode, I tried to do run `:call investigate#Investigate()`, it does not use what I have selected, but the word under cursor.

**Comment by keith** [comment]
This has been a limitation forever. I definitely think we can tackle this problem though. Firstly I've never tested sending queries with spaces to any of the providers. We need to test this, probably by having a configurable separator for each service. I'm assuming most will be `+`. Then we'd need to correctly map the command in visual mode to pass the correct text. Feel free to submit a PR in this direction!
