### ISSUE TITLE
Feature request: Surpport for looking up in zeal

### ISSUE THREAD

**Issue by QMonkey** [keith/investigate.vim#20]
[Zeal](https://zealdocs.org/) is an offline documentation browser inspired by Dash, available for Linux and Windows. Hope for supporting looking up in zeal. Thanks!

**Comment by keith** [comment]
I'm definitely open to supporting this. I think all that would be required would be duplicating some of the simple logic that exists for dash, and adding a new item to the [defaults array](https://github.com/keith/investigate.vim/blob/master/autoload/investigate/defaults.vim#L14) for this.

I haven't worked on this plugin too much lately but if someone wanted to submit a PR in this direction I would happily accept it!

**Comment by keith** [comment]
In the meantime, based on their documentation from [here](https://zealdocs.org/usage.html) you can use:

```
let g:investigate_command_for_python = '/usr/bin/zeal --query ^s'
```

Where you replace `python` with any language you choose.

**Comment by QMonkey** [comment]
In my opinion, may be the best way is add some config like 'g:investigate_use_docset', and the investigate.vim will auto choose dash or zeal. However, thank you anyway!

**Comment by keith** [comment]
I'm totally on board with PRs in this direction if you're still interested in it!
