### ISSUE TITLE
Ruby documentation is defunct

### ISSUE THREAD

**Issue by devlinzed** [keith/investigate.vim#24]
[Investigate uses omniref for Ruby documentation](https://github.com/keith/investigate.vim/blob/master/autoload/investigate/defaults.vim#L36), which was shut down a few months ago.  I wanted to make a pull request but couldn't find an alternative with feature parity.  Right now, though, it's broken.

**Comment by keith** [comment]
Thanks for filing this. I will look for a different site next time I'm on my computer. If you find one in the meantime please add it here or submit a PR with it!

**Comment by devlinzed** [comment]
I can find API docs for Ruby and for Rails but not Ruby and Rails like omniref.  I might not be googling the right thing; sorry I'm not more helpful.

**Comment by keith** [comment]
It doesn't particularly have to include rails IMO. If users want rails docs to be searched, as well as ruby stdlib docs, they can configure that I guess.
